apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-internal-net-samezone
spec:
  selector: "all()"
  namespaceSelector: "network-zone == 'internal-net'"
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      source:
        namespaceSelector: "network-zone == 'internal-net'"
  egress:
    - action: Allow
      destination:
        namespaceSelector: "network-zone == 'internal-net'"
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: allow-external-net-samezone
spec:
  selector: "all()"
  namespaceSelector: "network-zone == 'external-net'"
  types:
    - Ingress
    - Egress
  ingress:
    - action: Allow
      source:
        namespaceSelector: "network-zone == 'external-net'"
  egress:
    - action: Allow
      destination:
        namespaceSelector: "network-zone == 'external-net'"
