apiVersion: v2
name: my-ingress-nginx-chart
description: A Helm chart deploying two ingress-nginx instances
type: application
version: 0.1.0

dependencies:
  - name: ingress-nginx
    version: "4.12.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    alias: ingress-nginx-internal
  - name: ingress-nginx
    version: "4.12.3"
    repository: "https://kubernetes.github.io/ingress-nginx"
    alias: ingress-nginx-external
