apiVersion: v1
kind: Namespace
metadata:
  name: ingress-internal
  labels:
    network-zone: internal-net
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-external
  labels:
    network-zone: external-net
