apiVersion: v1
kind: Namespace
metadata:
  name: ingress-internal
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    network-zone: internal-net
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-external
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    network-zone: external-net
