apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-zone
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              network-zone: {{ .Values.zone }}
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              network-zone: {{ .Values.zone }}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
