apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.label }}
spec:
  containers:
    - name: httpd
      image: {{ .Values.image }}
      ports:
        - containerPort: {{ .Values.port }}
